Document pseudo-p attribute for localC
r-spatial/spdep pull request #73
Opened 2022-01-10 14:22 UTC by JosiahParry

This PR addresses https://github.com/r-spatial/spdep/issues/72

It 1) adds column names to `pseudo-p` attribute when `conditional = FALSE` and 2) adds output value documentation to `localC.Rd`.

2022-01-10 14:51 UTC, rsbivand approved these changes

2022-01-10 15:03 UTC, rsbivand requested changes
\item{Var.Ci}{standard deviate ... is \item{Var.Ci}{variance ...

The original MC test is total: `conditional=FALSE` (which I think is not what rgeoda does), I prefer `conditional=TRUE` which follows the local Moran implementation, probably the default should follow rgeoda. I didn't check against rgeoda yet, sorry.

2022-01-11 09:43 UTC, rsbivand approved these changes

2022-01-11 09:44 UTC, merged

2022-01-11 12:24 UTC, JosiahParry commented
Thanks! :)